import type { FeatureCollection, LineString, Polygon } from 'geojson'

/**
 * Real geological context layers from official Argentine datasets.
 *
 * Sources:
 *   - Hydrography: IGN Argentina WFS (lineas_de_aguas_continentales)
 *   - Rock outcrops: IGN Argentina WFS (edafologia_afloramiento_rocoso)
 *
 * Generated by scripts/fetch_ign_layers.py
 * Project AOI: San Juan Andes, Argentina (~-30.18, -69.35)
 */

export interface RiverProperties {
  name: string
  kind: 'perennial' | 'intermittent'
  source: string
}

export interface OutcropProperties {
  name: string
  source: string
}

export const riversGeoJSON: FeatureCollection<LineString, RiverProperties> =
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo del Agua Negra",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.2568,
            -30.2348
          ],
          [
            -69.2562,
            -30.2341
          ],
          [
            -69.2537,
            -30.2338
          ],
          [
            -69.2501,
            -30.2316
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo del Agua Negra",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3012,
            -30.2614
          ],
          [
            -69.2964,
            -30.2586
          ],
          [
            -69.2943,
            -30.2537
          ],
          [
            -69.2925,
            -30.2528
          ],
          [
            -69.289,
            -30.2485
          ],
          [
            -69.2864,
            -30.247
          ],
          [
            -69.2843,
            -30.2439
          ],
          [
            -69.2824,
            -30.2425
          ],
          [
            -69.2793,
            -30.2419
          ],
          [
            -69.2705,
            -30.2367
          ],
          [
            -69.2661,
            -30.2361
          ],
          [
            -69.2607,
            -30.2361
          ],
          [
            -69.2568,
            -30.2348
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo del Agua Negra",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.2428,
            -30.2331
          ],
          [
            -69.2419,
            -30.2334
          ],
          [
            -69.2393,
            -30.2329
          ],
          [
            -69.2379,
            -30.2316
          ],
          [
            -69.2347,
            -30.2312
          ],
          [
            -69.2334,
            -30.2302
          ],
          [
            -69.228,
            -30.2284
          ],
          [
            -69.226,
            -30.2264
          ],
          [
            -69.2234,
            -30.2254
          ],
          [
            -69.2207,
            -30.2235
          ],
          [
            -69.2123,
            -30.2203
          ],
          [
            -69.2088,
            -30.2171
          ],
          [
            -69.2038,
            -30.2151
          ],
          [
            -69.2024,
            -30.2134
          ],
          [
            -69.1969,
            -30.2099
          ],
          [
            -69.1957,
            -30.2095
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo del Agua Negra",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.2501,
            -30.2316
          ],
          [
            -69.2428,
            -30.2331
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo del Agua Negra",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.393,
            -30.3135
          ],
          [
            -69.3873,
            -30.312
          ],
          [
            -69.3849,
            -30.3106
          ],
          [
            -69.3797,
            -30.3088
          ],
          [
            -69.3765,
            -30.3082
          ],
          [
            -69.3754,
            -30.3068
          ],
          [
            -69.3715,
            -30.3048
          ],
          [
            -69.3659,
            -30.3032
          ],
          [
            -69.3597,
            -30.2994
          ],
          [
            -69.3585,
            -30.2982
          ],
          [
            -69.3569,
            -30.2975
          ],
          [
            -69.3549,
            -30.2977
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo del Agua Negra",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.341,
            -30.2893
          ],
          [
            -69.3363,
            -30.2865
          ],
          [
            -69.3341,
            -30.2837
          ],
          [
            -69.3319,
            -30.2827
          ],
          [
            -69.3296,
            -30.2809
          ],
          [
            -69.3284,
            -30.2802
          ],
          [
            -69.3246,
            -30.2795
          ],
          [
            -69.3196,
            -30.2736
          ],
          [
            -69.3153,
            -30.2706
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo del Agua Negra",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3549,
            -30.2977
          ],
          [
            -69.3494,
            -30.2956
          ],
          [
            -69.3485,
            -30.2947
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo del Agua Negra",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3474,
            -30.2944
          ],
          [
            -69.3439,
            -30.2909
          ],
          [
            -69.341,
            -30.2893
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo del Agua Negra",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3153,
            -30.2706
          ],
          [
            -69.3129,
            -30.2678
          ],
          [
            -69.3052,
            -30.2644
          ],
          [
            -69.3012,
            -30.2614
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo del Agua Negra",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3485,
            -30.2947
          ],
          [
            -69.3474,
            -30.2944
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4403,
            -30.1993
          ],
          [
            -69.421,
            -30.2065
          ],
          [
            -69.4015,
            -30.2218
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3775,
            -30.2245
          ],
          [
            -69.3703,
            -30.2226
          ],
          [
            -69.3569,
            -30.2225
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4124,
            -30.2403
          ],
          [
            -69.3976,
            -30.2386
          ],
          [
            -69.3741,
            -30.229
          ],
          [
            -69.3669,
            -30.2246
          ],
          [
            -69.3569,
            -30.2225
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3859,
            -30.2424
          ],
          [
            -69.3738,
            -30.2407
          ],
          [
            -69.3632,
            -30.2372
          ],
          [
            -69.3523,
            -30.2377
          ],
          [
            -69.34,
            -30.235
          ],
          [
            -69.3293,
            -30.2361
          ],
          [
            -69.32,
            -30.2346
          ],
          [
            -69.3092,
            -30.2351
          ],
          [
            -69.3052,
            -30.234
          ],
          [
            -69.3018,
            -30.2305
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.484,
            -30.2227
          ],
          [
            -69.4752,
            -30.2242
          ],
          [
            -69.4577,
            -30.2235
          ],
          [
            -69.4493,
            -30.2275
          ],
          [
            -69.437,
            -30.2289
          ],
          [
            -69.4157,
            -30.2252
          ],
          [
            -69.3874,
            -30.2272
          ],
          [
            -69.3775,
            -30.2245
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3569,
            -30.2225
          ],
          [
            -69.3499,
            -30.2208
          ],
          [
            -69.3446,
            -30.2214
          ],
          [
            -69.327,
            -30.2255
          ],
          [
            -69.3158,
            -30.2264
          ],
          [
            -69.3018,
            -30.2305
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3893,
            -30.19
          ],
          [
            -69.361,
            -30.1862
          ],
          [
            -69.3451,
            -30.1859
          ],
          [
            -69.3255,
            -30.1875
          ],
          [
            -69.3148,
            -30.1904
          ],
          [
            -69.31,
            -30.1895
          ],
          [
            -69.2981,
            -30.1805
          ],
          [
            -69.2951,
            -30.1801
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4969,
            -30.1423
          ],
          [
            -69.4849,
            -30.1437
          ],
          [
            -69.4792,
            -30.1412
          ],
          [
            -69.4696,
            -30.1447
          ],
          [
            -69.4586,
            -30.1428
          ],
          [
            -69.4528,
            -30.1459
          ],
          [
            -69.4452,
            -30.1439
          ],
          [
            -69.4038,
            -30.1452
          ],
          [
            -69.3978,
            -30.1428
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.2951,
            -30.1801
          ],
          [
            -69.2855,
            -30.185
          ],
          [
            -69.272,
            -30.1828
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4305,
            -30.1924
          ],
          [
            -69.4179,
            -30.1952
          ],
          [
            -69.4074,
            -30.1949
          ],
          [
            -69.398,
            -30.1975
          ],
          [
            -69.3819,
            -30.1986
          ],
          [
            -69.357,
            -30.2065
          ],
          [
            -69.327,
            -30.2086
          ],
          [
            -69.3011,
            -30.2152
          ],
          [
            -69.2947,
            -30.2148
          ],
          [
            -69.2887,
            -30.2177
          ],
          [
            -69.2818,
            -30.2173
          ],
          [
            -69.2747,
            -30.2192
          ],
          [
            -69.269,
            -30.2244
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.2942,
            -30.1527
          ],
          [
            -69.2915,
            -30.1549
          ],
          [
            -69.2811,
            -30.1582
          ],
          [
            -69.2733,
            -30.1642
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4665,
            -30.1314
          ],
          [
            -69.4446,
            -30.1294
          ],
          [
            -69.4425,
            -30.1279
          ],
          [
            -69.4355,
            -30.1278
          ],
          [
            -69.4332,
            -30.1259
          ],
          [
            -69.4233,
            -30.1246
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4015,
            -30.2218
          ],
          [
            -69.3948,
            -30.2236
          ],
          [
            -69.3775,
            -30.2245
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.2998,
            -30.221
          ],
          [
            -69.2817,
            -30.2272
          ],
          [
            -69.2739,
            -30.2269
          ],
          [
            -69.269,
            -30.2244
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3457,
            -30.1201
          ],
          [
            -69.3234,
            -30.1366
          ],
          [
            -69.312,
            -30.1422
          ],
          [
            -69.2885,
            -30.1497
          ],
          [
            -69.2636,
            -30.1551
          ],
          [
            -69.2526,
            -30.1525
          ],
          [
            -69.24,
            -30.1533
          ],
          [
            -69.2331,
            -30.1522
          ],
          [
            -69.2154,
            -30.1561
          ],
          [
            -69.2108,
            -30.1552
          ],
          [
            -69.2043,
            -30.1606
          ],
          [
            -69.1965,
            -30.1636
          ],
          [
            -69.1917,
            -30.1636
          ],
          [
            -69.1844,
            -30.1687
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3743,
            -30.1285
          ],
          [
            -69.3548,
            -30.1267
          ],
          [
            -69.3452,
            -30.1325
          ],
          [
            -69.319,
            -30.1407
          ],
          [
            -69.3135,
            -30.1447
          ],
          [
            -69.3104,
            -30.1443
          ],
          [
            -69.2997,
            -30.1486
          ],
          [
            -69.2942,
            -30.1527
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.515,
            -30.2339
          ],
          [
            -69.4977,
            -30.2416
          ],
          [
            -69.4833,
            -30.2411
          ],
          [
            -69.4768,
            -30.2445
          ],
          [
            -69.4666,
            -30.2443
          ],
          [
            -69.4599,
            -30.2472
          ],
          [
            -69.4543,
            -30.2471
          ],
          [
            -69.4493,
            -30.2489
          ],
          [
            -69.4205,
            -30.2468
          ],
          [
            -69.4148,
            -30.2481
          ],
          [
            -69.4099,
            -30.2461
          ],
          [
            -69.3952,
            -30.2445
          ],
          [
            -69.3886,
            -30.2415
          ],
          [
            -69.3859,
            -30.2424
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4354,
            -30.2184
          ],
          [
            -69.4147,
            -30.2226
          ],
          [
            -69.4015,
            -30.2218
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4794,
            -30.1325
          ],
          [
            -69.4585,
            -30.124
          ],
          [
            -69.4461,
            -30.1211
          ],
          [
            -69.4374,
            -30.121
          ],
          [
            -69.4233,
            -30.1246
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.402,
            -30.0945
          ],
          [
            -69.3974,
            -30.0957
          ],
          [
            -69.3862,
            -30.1024
          ],
          [
            -69.3832,
            -30.1065
          ],
          [
            -69.3789,
            -30.109
          ],
          [
            -69.3696,
            -30.1121
          ],
          [
            -69.3583,
            -30.1131
          ],
          [
            -69.3457,
            -30.1201
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.2951,
            -30.1801
          ],
          [
            -69.2883,
            -30.1792
          ],
          [
            -69.2776,
            -30.1813
          ],
          [
            -69.2714,
            -30.1784
          ],
          [
            -69.2657,
            -30.18
          ],
          [
            -69.2505,
            -30.1798
          ],
          [
            -69.2395,
            -30.1761
          ],
          [
            -69.2309,
            -30.1789
          ],
          [
            -69.2267,
            -30.1772
          ],
          [
            -69.221,
            -30.1773
          ],
          [
            -69.2157,
            -30.1739
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5184,
            -30.1412
          ],
          [
            -69.5106,
            -30.1426
          ],
          [
            -69.492,
            -30.1405
          ],
          [
            -69.4861,
            -30.1378
          ],
          [
            -69.4652,
            -30.1335
          ],
          [
            -69.4517,
            -30.134
          ],
          [
            -69.4382,
            -30.1323
          ],
          [
            -69.4255,
            -30.134
          ],
          [
            -69.4101,
            -30.1324
          ],
          [
            -69.4058,
            -30.1351
          ],
          [
            -69.3939,
            -30.1366
          ],
          [
            -69.3876,
            -30.1405
          ],
          [
            -69.3811,
            -30.1414
          ],
          [
            -69.3768,
            -30.1441
          ],
          [
            -69.365,
            -30.1453
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.365,
            -30.1453
          ],
          [
            -69.3611,
            -30.1441
          ],
          [
            -69.3471,
            -30.145
          ],
          [
            -69.3326,
            -30.1491
          ],
          [
            -69.307,
            -30.149
          ],
          [
            -69.2962,
            -30.1525
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.466,
            -30.1504
          ],
          [
            -69.4506,
            -30.1487
          ],
          [
            -69.442,
            -30.1513
          ],
          [
            -69.4231,
            -30.1516
          ],
          [
            -69.4092,
            -30.1551
          ],
          [
            -69.3914,
            -30.1555
          ],
          [
            -69.3799,
            -30.1591
          ],
          [
            -69.3639,
            -30.1596
          ],
          [
            -69.354,
            -30.1562
          ],
          [
            -69.3327,
            -30.1528
          ],
          [
            -69.2962,
            -30.1525
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4187,
            -30.1812
          ],
          [
            -69.4031,
            -30.18
          ],
          [
            -69.3979,
            -30.1763
          ],
          [
            -69.3881,
            -30.1743
          ],
          [
            -69.3819,
            -30.1748
          ],
          [
            -69.363,
            -30.1694
          ],
          [
            -69.3477,
            -30.1704
          ],
          [
            -69.3342,
            -30.1681
          ],
          [
            -69.3055,
            -30.1681
          ],
          [
            -69.2878,
            -30.1641
          ],
          [
            -69.2771,
            -30.1631
          ],
          [
            -69.2733,
            -30.1642
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4387,
            -30.235
          ],
          [
            -69.4124,
            -30.2403
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4704,
            -30.1393
          ],
          [
            -69.4571,
            -30.1381
          ],
          [
            -69.4481,
            -30.1395
          ],
          [
            -69.4332,
            -30.1372
          ],
          [
            -69.4132,
            -30.1406
          ],
          [
            -69.4072,
            -30.1384
          ],
          [
            -69.3978,
            -30.1428
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3978,
            -30.1428
          ],
          [
            -69.3829,
            -30.1458
          ],
          [
            -69.365,
            -30.1453
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4744,
            -30.1053
          ],
          [
            -69.4681,
            -30.1067
          ],
          [
            -69.4591,
            -30.1053
          ],
          [
            -69.4424,
            -30.1123
          ],
          [
            -69.3976,
            -30.1094
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5054,
            -30.1471
          ],
          [
            -69.4832,
            -30.1558
          ],
          [
            -69.4753,
            -30.1617
          ],
          [
            -69.4558,
            -30.1638
          ],
          [
            -69.4421,
            -30.1691
          ],
          [
            -69.4374,
            -30.1726
          ],
          [
            -69.4278,
            -30.1744
          ],
          [
            -69.4187,
            -30.1812
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4347,
            -30.186
          ],
          [
            -69.424,
            -30.1826
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.424,
            -30.1826
          ],
          [
            -69.4187,
            -30.1812
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4564,
            -30.2444
          ],
          [
            -69.4413,
            -30.2446
          ],
          [
            -69.4124,
            -30.2403
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4687,
            -30.1149
          ],
          [
            -69.4639,
            -30.1152
          ],
          [
            -69.4603,
            -30.1172
          ],
          [
            -69.4453,
            -30.1175
          ],
          [
            -69.4306,
            -30.1157
          ],
          [
            -69.4189,
            -30.1187
          ],
          [
            -69.409,
            -30.1233
          ],
          [
            -69.3996,
            -30.1247
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4233,
            -30.1246
          ],
          [
            -69.3996,
            -30.1247
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4423,
            -30.1307
          ],
          [
            -69.4114,
            -30.1278
          ],
          [
            -69.3843,
            -30.1315
          ],
          [
            -69.3743,
            -30.1285
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3996,
            -30.1247
          ],
          [
            -69.3743,
            -30.1285
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4468,
            -30.2615
          ],
          [
            -69.4255,
            -30.2595
          ],
          [
            -69.3859,
            -30.2424
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3018,
            -30.2305
          ],
          [
            -69.2883,
            -30.2296
          ],
          [
            -69.2803,
            -30.2309
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.2803,
            -30.2309
          ],
          [
            -69.2655,
            -30.2322
          ],
          [
            -69.2602,
            -30.2306
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.2962,
            -30.1525
          ],
          [
            -69.2942,
            -30.1527
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.2717,
            -30.1447
          ],
          [
            -69.2544,
            -30.1479
          ],
          [
            -69.2454,
            -30.1447
          ],
          [
            -69.2375,
            -30.146
          ],
          [
            -69.2092,
            -30.1314
          ],
          [
            -69.2015,
            -30.1299
          ],
          [
            -69.1979,
            -30.1313
          ],
          [
            -69.1753,
            -30.1304
          ],
          [
            -69.1687,
            -30.1326
          ],
          [
            -69.1612,
            -30.1324
          ],
          [
            -69.1523,
            -30.1297
          ],
          [
            -69.1313,
            -30.1344
          ],
          [
            -69.1228,
            -30.1392
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4756,
            -30.1644
          ],
          [
            -69.4666,
            -30.1653
          ],
          [
            -69.4536,
            -30.1765
          ],
          [
            -69.4408,
            -30.1766
          ],
          [
            -69.4385,
            -30.1783
          ],
          [
            -69.4307,
            -30.179
          ],
          [
            -69.424,
            -30.1826
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.3976,
            -30.1094
          ],
          [
            -69.38,
            -30.1125
          ],
          [
            -69.3727,
            -30.116
          ],
          [
            -69.3553,
            -30.1161
          ],
          [
            -69.3457,
            -30.1201
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.2733,
            -30.1642
          ],
          [
            -69.2596,
            -30.1647
          ],
          [
            -69.2558,
            -30.1662
          ],
          [
            -69.2462,
            -30.1653
          ],
          [
            -69.2413,
            -30.1628
          ],
          [
            -69.2333,
            -30.1637
          ],
          [
            -69.2263,
            -30.1651
          ],
          [
            -69.2163,
            -30.1713
          ],
          [
            -69.2037,
            -30.1749
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4305,
            -30.1924
          ],
          [
            -69.4273,
            -30.1909
          ],
          [
            -69.3929,
            -30.1912
          ],
          [
            -69.3893,
            -30.19
          ]
        ]
      }
    }
  ]
} as FeatureCollection<LineString, RiverProperties>

export const outcropsGeoJSON: FeatureCollection<Polygon, OutcropProperties> =
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "Afloramiento Rocoso",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.237,
              -30.2136
            ],
            [
              -69.2285,
              -30.2276
            ],
            [
              -69.2378,
              -30.2331
            ],
            [
              -69.2794,
              -30.2305
            ],
            [
              -69.301,
              -30.217
            ],
            [
              -69.2839,
              -30.1989
            ],
            [
              -69.2529,
              -30.2124
            ],
            [
              -69.2794,
              -30.1969
            ],
            [
              -69.2628,
              -30.1913
            ],
            [
              -69.2512,
              -30.1926
            ],
            [
              -69.237,
              -30.2136
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Afloramiento Rocoso",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.3116,
              -30.1424
            ],
            [
              -69.3083,
              -30.1212
            ],
            [
              -69.3008,
              -30.1202
            ],
            [
              -69.3009,
              -30.1338
            ],
            [
              -69.3116,
              -30.1424
            ]
          ]
        ]
      }
    }
  ]
} as FeatureCollection<Polygon, OutcropProperties>

/** Layer metadata for UI controls */
export const GEOLOGY_LAYERS = {
  rivers: { label: 'Rivers & Streams', color: '#3b82f6' },
  outcrops: { label: 'Rock Outcrops', color: '#a78bfa' },
} as const

export type GeologyLayerKey = keyof typeof GEOLOGY_LAYERS
