import type { FeatureCollection, LineString, Point, Polygon } from 'geojson'

/**
 * Real geological context layers from official Argentine datasets.
 *
 * Sources:
 *   - Hydrography: IGN Argentina WFS (lineas_de_aguas_continentales)
 *   - Water bodies: IGN Argentina WFS (areas_de_aguas_continentales)
 *   - Glaciers: IGN Argentina WFS (puntos_de_glaciologia_BJ030)
 *   - International boundary: IGN Argentina WFS (linea_de_limite_FA004)
 *   - Mining points: IGN/SEGEMAR (puntos_de_extraccion_AA010)
 *
 * Generated by scripts/fetch_ign_layers.py
 * Project AOI: Filo del Sol Cu-Au, Argentina-Chile border (~-28.49, -69.66)
 */

export interface RiverProperties {
  name: string
  kind: 'perennial' | 'intermittent'
  source: string
}

export interface WaterBodyProperties {
  name: string
  kind: 'perennial' | 'intermittent'
  source: string
}

export interface GlacierProperties {
  name: string
  source: string
}

export interface BoundaryProperties {
  name: string
  source: string
}

export interface MineProperties {
  name: string
  source: string
}

export const riversGeoJSON: FeatureCollection<LineString, RiverProperties> =
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Manflas",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.8006,
            -28.6112
          ],
          [
            -69.8139,
            -28.6021
          ],
          [
            -69.8353,
            -28.5941
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Manflas",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.8405,
            -28.5889
          ],
          [
            -69.8439,
            -28.5898
          ],
          [
            -69.8551,
            -28.5868
          ],
          [
            -69.8656,
            -28.587
          ],
          [
            -69.8687,
            -28.5834
          ],
          [
            -69.879,
            -28.5799
          ],
          [
            -69.8815,
            -28.5747
          ],
          [
            -69.8878,
            -28.5682
          ],
          [
            -69.8892,
            -28.5633
          ],
          [
            -69.8931,
            -28.5598
          ],
          [
            -69.8991,
            -28.5578
          ],
          [
            -69.9024,
            -28.5539
          ],
          [
            -69.9027,
            -28.5511
          ],
          [
            -69.9168,
            -28.547
          ],
          [
            -69.9231,
            -28.5477
          ],
          [
            -69.9276,
            -28.5448
          ],
          [
            -69.9354,
            -28.5441
          ],
          [
            -69.9463,
            -28.5392
          ],
          [
            -69.9501,
            -28.5351
          ],
          [
            -69.9575,
            -28.5332
          ],
          [
            -69.9624,
            -28.5292
          ],
          [
            -69.9673,
            -28.5149
          ],
          [
            -69.9666,
            -28.5075
          ],
          [
            -69.9719,
            -28.5008
          ],
          [
            -69.9733,
            -28.4937
          ],
          [
            -69.9774,
            -28.4876
          ],
          [
            -69.9738,
            -28.4829
          ],
          [
            -69.9742,
            -28.4804
          ],
          [
            -69.9712,
            -28.4764
          ],
          [
            -69.9697,
            -28.4695
          ],
          [
            -69.9704,
            -28.4624
          ],
          [
            -69.9718,
            -28.4615
          ],
          [
            -69.9699,
            -28.4542
          ],
          [
            -69.9744,
            -28.4479
          ],
          [
            -69.9718,
            -28.4408
          ],
          [
            -69.962,
            -28.4328
          ],
          [
            -69.9634,
            -28.4274
          ],
          [
            -69.9662,
            -28.4243
          ],
          [
            -69.9616,
            -28.4161
          ],
          [
            -69.9601,
            -28.4077
          ],
          [
            -69.963,
            -28.4018
          ],
          [
            -69.9656,
            -28.3908
          ],
          [
            -69.9629,
            -28.3772
          ],
          [
            -69.964,
            -28.3689
          ],
          [
            -69.9605,
            -28.3652
          ],
          [
            -69.9623,
            -28.3605
          ],
          [
            -69.9615,
            -28.3575
          ],
          [
            -69.9665,
            -28.354
          ],
          [
            -69.9664,
            -28.3467
          ],
          [
            -69.9702,
            -28.3414
          ],
          [
            -69.9696,
            -28.3333
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada del Tolar",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.8064,
            -28.5032
          ],
          [
            -69.8205,
            -28.4961
          ],
          [
            -69.8229,
            -28.4921
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada del R\u00edo Grande",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.7034,
            -28.594
          ],
          [
            -69.7046,
            -28.5987
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo del Potro",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.7635,
            -28.338
          ],
          [
            -69.757,
            -28.3307
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Manflas",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.7558,
            -28.6252
          ],
          [
            -69.757,
            -28.6273
          ],
          [
            -69.7607,
            -28.628
          ],
          [
            -69.7717,
            -28.623
          ],
          [
            -69.779,
            -28.6231
          ],
          [
            -69.7856,
            -28.6199
          ],
          [
            -69.7937,
            -28.6192
          ],
          [
            -69.7982,
            -28.6158
          ],
          [
            -69.8006,
            -28.6112
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada las Piedras",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.7086,
            -28.3505
          ],
          [
            -69.7105,
            -28.3463
          ],
          [
            -69.7194,
            -28.3419
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo del Potro",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.7854,
            -28.339
          ],
          [
            -69.7767,
            -28.342
          ],
          [
            -69.7664,
            -28.3378
          ],
          [
            -69.7635,
            -28.338
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo Laguna de Montosa",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6778,
            -28.3898
          ],
          [
            -69.687,
            -28.3857
          ],
          [
            -69.715,
            -28.3876
          ],
          [
            -69.7294,
            -28.395
          ],
          [
            -69.7369,
            -28.3957
          ],
          [
            -69.7569,
            -28.404
          ],
          [
            -69.7639,
            -28.4034
          ],
          [
            -69.7688,
            -28.4003
          ],
          [
            -69.7765,
            -28.4025
          ],
          [
            -69.7808,
            -28.4055
          ],
          [
            -69.7896,
            -28.4054
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada del Marancel",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.7175,
            -28.4514
          ],
          [
            -69.7237,
            -28.4564
          ],
          [
            -69.7256,
            -28.465
          ],
          [
            -69.7281,
            -28.4686
          ],
          [
            -69.7373,
            -28.472
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada del Marancel",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6496,
            -28.4359
          ],
          [
            -69.6661,
            -28.4315
          ],
          [
            -69.6724,
            -28.4282
          ],
          [
            -69.6755,
            -28.4294
          ],
          [
            -69.6792,
            -28.4283
          ],
          [
            -69.6886,
            -28.431
          ],
          [
            -69.6918,
            -28.4303
          ],
          [
            -69.6962,
            -28.433
          ],
          [
            -69.7028,
            -28.4336
          ],
          [
            -69.7069,
            -28.4368
          ],
          [
            -69.708,
            -28.4419
          ],
          [
            -69.7115,
            -28.4472
          ],
          [
            -69.7175,
            -28.4514
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Manflas",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.8353,
            -28.5941
          ],
          [
            -69.8363,
            -28.5907
          ],
          [
            -69.8405,
            -28.5889
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo Laguna de Montosa",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6614,
            -28.4004
          ],
          [
            -69.6663,
            -28.4043
          ],
          [
            -69.6764,
            -28.4044
          ],
          [
            -69.6807,
            -28.4013
          ],
          [
            -69.6816,
            -28.398
          ],
          [
            -69.6795,
            -28.3901
          ],
          [
            -69.6803,
            -28.3882
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada del Tolar",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.8229,
            -28.4921
          ],
          [
            -69.8634,
            -28.4806
          ],
          [
            -69.8698,
            -28.4804
          ],
          [
            -69.8791,
            -28.4838
          ],
          [
            -69.9051,
            -28.4726
          ],
          [
            -69.9069,
            -28.4707
          ],
          [
            -69.9101,
            -28.4563
          ],
          [
            -69.9081,
            -28.4508
          ],
          [
            -69.9082,
            -28.4456
          ],
          [
            -69.9105,
            -28.4399
          ],
          [
            -69.9132,
            -28.438
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada del R\u00edo Grande",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.7046,
            -28.5987
          ],
          [
            -69.7053,
            -28.6031
          ],
          [
            -69.7033,
            -28.6076
          ],
          [
            -69.7066,
            -28.6101
          ],
          [
            -69.7144,
            -28.6277
          ],
          [
            -69.7182,
            -28.6299
          ],
          [
            -69.7196,
            -28.6342
          ],
          [
            -69.7333,
            -28.6503
          ],
          [
            -69.7367,
            -28.6628
          ],
          [
            -69.7413,
            -28.667
          ],
          [
            -69.7425,
            -28.6714
          ],
          [
            -69.7522,
            -28.6839
          ],
          [
            -69.7542,
            -28.6969
          ],
          [
            -69.7618,
            -28.701
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada del R\u00edo Grande",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.701,
            -28.5887
          ],
          [
            -69.7034,
            -28.594
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo del Potro",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.757,
            -28.3307
          ],
          [
            -69.7509,
            -28.314
          ],
          [
            -69.7396,
            -28.3006
          ],
          [
            -69.7388,
            -28.2875
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Ramadillas o del Medio",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5352,
            -28.303
          ],
          [
            -69.5299,
            -28.2932
          ],
          [
            -69.5217,
            -28.2837
          ],
          [
            -69.5218,
            -28.276
          ],
          [
            -69.5275,
            -28.2642
          ],
          [
            -69.5325,
            -28.2607
          ],
          [
            -69.5389,
            -28.2512
          ],
          [
            -69.5408,
            -28.2426
          ],
          [
            -69.5519,
            -28.2265
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Helados",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.666,
            -28.3115
          ],
          [
            -69.6668,
            -28.3065
          ],
          [
            -69.6754,
            -28.301
          ],
          [
            -69.6873,
            -28.2979
          ],
          [
            -69.6909,
            -28.2955
          ],
          [
            -69.6972,
            -28.296
          ],
          [
            -69.7025,
            -28.2903
          ],
          [
            -69.7092,
            -28.2726
          ],
          [
            -69.712,
            -28.2725
          ],
          [
            -69.7319,
            -28.2632
          ],
          [
            -69.7366,
            -28.2583
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada las Piedras",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.7194,
            -28.3419
          ],
          [
            -69.7227,
            -28.3393
          ],
          [
            -69.7262,
            -28.3327
          ],
          [
            -69.7274,
            -28.3225
          ],
          [
            -69.7304,
            -28.3212
          ],
          [
            -69.7285,
            -28.3143
          ],
          [
            -69.7311,
            -28.3011
          ],
          [
            -69.729,
            -28.2956
          ],
          [
            -69.7311,
            -28.2917
          ],
          [
            -69.7388,
            -28.2875
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Helados",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5914,
            -28.2847
          ],
          [
            -69.5875,
            -28.2862
          ],
          [
            -69.5857,
            -28.2896
          ],
          [
            -69.5908,
            -28.3004
          ],
          [
            -69.5966,
            -28.3097
          ],
          [
            -69.6034,
            -28.3099
          ],
          [
            -69.6063,
            -28.312
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5078,
            -28.4272
          ],
          [
            -69.5069,
            -28.4234
          ],
          [
            -69.5012,
            -28.4174
          ],
          [
            -69.4978,
            -28.416
          ],
          [
            -69.488,
            -28.414
          ],
          [
            -69.4768,
            -28.416
          ],
          [
            -69.4695,
            -28.4151
          ],
          [
            -69.4673,
            -28.4167
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4673,
            -28.4167
          ],
          [
            -69.4629,
            -28.4201
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4534,
            -28.4329
          ],
          [
            -69.4524,
            -28.4363
          ],
          [
            -69.4453,
            -28.4386
          ],
          [
            -69.4411,
            -28.4428
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.4629,
            -28.4201
          ],
          [
            -69.4593,
            -28.4241
          ],
          [
            -69.4587,
            -28.4289
          ],
          [
            -69.4534,
            -28.4329
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5126,
            -28.4309
          ],
          [
            -69.5078,
            -28.4272
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5332,
            -28.4181
          ],
          [
            -69.5198,
            -28.4306
          ],
          [
            -69.5126,
            -28.4309
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6358,
            -28.411
          ],
          [
            -69.6307,
            -28.412
          ],
          [
            -69.6238,
            -28.4172
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5827,
            -28.4141
          ],
          [
            -69.5668,
            -28.4055
          ],
          [
            -69.5565,
            -28.4055
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5565,
            -28.4055
          ],
          [
            -69.5444,
            -28.414
          ],
          [
            -69.5332,
            -28.4181
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5929,
            -28.4168
          ],
          [
            -69.5899,
            -28.4159
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5899,
            -28.4159
          ],
          [
            -69.5871,
            -28.4152
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6057,
            -28.4193
          ],
          [
            -69.599,
            -28.419
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6142,
            -28.4186
          ],
          [
            -69.6057,
            -28.4193
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.599,
            -28.419
          ],
          [
            -69.5929,
            -28.4168
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5871,
            -28.4152
          ],
          [
            -69.5827,
            -28.4141
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6238,
            -28.4172
          ],
          [
            -69.6186,
            -28.4183
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6186,
            -28.4183
          ],
          [
            -69.6142,
            -28.4186
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Blanco",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6409,
            -28.4062
          ],
          [
            -69.6358,
            -28.411
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada del Marancel",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6447,
            -28.438
          ],
          [
            -69.6496,
            -28.4359
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Ramadillas o del Medio",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5611,
            -28.3281
          ],
          [
            -69.5513,
            -28.3251
          ],
          [
            -69.5489,
            -28.3221
          ],
          [
            -69.5434,
            -28.3194
          ],
          [
            -69.5352,
            -28.303
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo Ramadillas o del Medio",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5635,
            -28.3369
          ],
          [
            -69.5611,
            -28.3281
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Helados",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5983,
            -28.3706
          ],
          [
            -69.5929,
            -28.3605
          ],
          [
            -69.5911,
            -28.3413
          ],
          [
            -69.5844,
            -28.3385
          ],
          [
            -69.5815,
            -28.3353
          ],
          [
            -69.5821,
            -28.3304
          ],
          [
            -69.5857,
            -28.3299
          ],
          [
            -69.5889,
            -28.3272
          ],
          [
            -69.5955,
            -28.3163
          ],
          [
            -69.6005,
            -28.3134
          ],
          [
            -69.6223,
            -28.3095
          ],
          [
            -69.6311,
            -28.312
          ],
          [
            -69.6478,
            -28.3092
          ],
          [
            -69.6592,
            -28.3105
          ],
          [
            -69.6635,
            -28.307
          ],
          [
            -69.6671,
            -28.3063
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada del Tolar",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.805,
            -28.5053
          ],
          [
            -69.8064,
            -28.5032
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.593,
            -28.4981
          ],
          [
            -69.5834,
            -28.4952
          ],
          [
            -69.5784,
            -28.4904
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Mogotes",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6318,
            -28.4915
          ],
          [
            -69.6269,
            -28.5168
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6601,
            -28.4954
          ],
          [
            -69.6511,
            -28.4894
          ],
          [
            -69.6398,
            -28.4921
          ],
          [
            -69.6355,
            -28.4905
          ],
          [
            -69.6318,
            -28.4915
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.652,
            -28.4733
          ],
          [
            -69.6402,
            -28.4733
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Mogotes",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6316,
            -28.489
          ],
          [
            -69.6318,
            -28.4915
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6317,
            -28.5347
          ],
          [
            -69.6262,
            -28.5378
          ],
          [
            -69.6184,
            -28.5366
          ],
          [
            -69.6138,
            -28.5377
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Mogotes",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6141,
            -28.5317
          ],
          [
            -69.6138,
            -28.5377
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Mogotes",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6518,
            -28.4596
          ],
          [
            -69.6456,
            -28.4613
          ],
          [
            -69.6434,
            -28.4678
          ],
          [
            -69.6411,
            -28.4686
          ],
          [
            -69.6402,
            -28.4733
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Mogotes",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6402,
            -28.4733
          ],
          [
            -69.6378,
            -28.4752
          ],
          [
            -69.6316,
            -28.489
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.623,
            -28.4582
          ],
          [
            -69.629,
            -28.4642
          ],
          [
            -69.6317,
            -28.4736
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6317,
            -28.4736
          ],
          [
            -69.6263,
            -28.4805
          ],
          [
            -69.6316,
            -28.489
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6577,
            -28.5104
          ],
          [
            -69.6471,
            -28.5142
          ],
          [
            -69.6325,
            -28.5146
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Mogotes",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6242,
            -28.5251
          ],
          [
            -69.6141,
            -28.5317
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6501,
            -28.5199
          ],
          [
            -69.6397,
            -28.5205
          ],
          [
            -69.6325,
            -28.5146
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6325,
            -28.5146
          ],
          [
            -69.6269,
            -28.5168
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6493,
            -28.5269
          ],
          [
            -69.6434,
            -28.5299
          ],
          [
            -69.6385,
            -28.5302
          ],
          [
            -69.6313,
            -28.5256
          ],
          [
            -69.6242,
            -28.5251
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Mogotes",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6269,
            -28.5168
          ],
          [
            -69.6242,
            -28.5251
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6636,
            -28.476
          ],
          [
            -69.6572,
            -28.476
          ],
          [
            -69.652,
            -28.4733
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6609,
            -28.4664
          ],
          [
            -69.652,
            -28.4733
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.61,
            -28.5016
          ],
          [
            -69.6037,
            -28.5147
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6014,
            -28.5059
          ],
          [
            -69.6019,
            -28.5123
          ],
          [
            -69.6037,
            -28.5147
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6053,
            -28.519
          ],
          [
            -69.6141,
            -28.5317
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5931,
            -28.5214
          ],
          [
            -69.6053,
            -28.519
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6037,
            -28.5147
          ],
          [
            -69.6053,
            -28.519
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Arroyo Pircas de los Bueyes",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.592,
            -28.4528
          ],
          [
            -69.5867,
            -28.457
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6129,
            -28.4433
          ],
          [
            -69.6049,
            -28.4491
          ],
          [
            -69.592,
            -28.4528
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.604,
            -28.4419
          ],
          [
            -69.592,
            -28.4528
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6022,
            -28.473
          ],
          [
            -69.5855,
            -28.4748
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6003,
            -28.4655
          ],
          [
            -69.5851,
            -28.4726
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.601,
            -28.4779
          ],
          [
            -69.5906,
            -28.479
          ],
          [
            -69.5854,
            -28.4811
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6024,
            -28.4857
          ],
          [
            -69.5901,
            -28.4866
          ],
          [
            -69.5838,
            -28.4852
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5958,
            -28.4297
          ],
          [
            -69.5938,
            -28.4269
          ],
          [
            -69.5944,
            -28.4209
          ],
          [
            -69.5899,
            -28.4159
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6421,
            -28.4441
          ],
          [
            -69.6411,
            -28.4494
          ],
          [
            -69.6388,
            -28.4523
          ],
          [
            -69.6409,
            -28.4564
          ],
          [
            -69.636,
            -28.4612
          ],
          [
            -69.6346,
            -28.4643
          ],
          [
            -69.6352,
            -28.4696
          ],
          [
            -69.6317,
            -28.4736
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6177,
            -28.4506
          ],
          [
            -69.6185,
            -28.4477
          ],
          [
            -69.6165,
            -28.4434
          ],
          [
            -69.6186,
            -28.4397
          ],
          [
            -69.6191,
            -28.4334
          ],
          [
            -69.6057,
            -28.4193
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6334,
            -28.4247
          ],
          [
            -69.6261,
            -28.4232
          ],
          [
            -69.6186,
            -28.4183
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6266,
            -28.4299
          ],
          [
            -69.6221,
            -28.4266
          ],
          [
            -69.6184,
            -28.4209
          ],
          [
            -69.6142,
            -28.4186
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6593,
            -28.5429
          ],
          [
            -69.6498,
            -28.556
          ],
          [
            -69.6489,
            -28.5646
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6411,
            -28.5531
          ],
          [
            -69.6365,
            -28.5546
          ],
          [
            -69.6296,
            -28.5531
          ],
          [
            -69.6171,
            -28.5467
          ],
          [
            -69.6109,
            -28.5455
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Mogotes",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6109,
            -28.5455
          ],
          [
            -69.605,
            -28.5487
          ],
          [
            -69.6016,
            -28.5525
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Mogotes",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6127,
            -28.5411
          ],
          [
            -69.6109,
            -28.5455
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6305,
            -28.5406
          ],
          [
            -69.6196,
            -28.5394
          ],
          [
            -69.6127,
            -28.5411
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Mogotes",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6138,
            -28.5377
          ],
          [
            -69.6127,
            -28.5411
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6468,
            -28.5439
          ],
          [
            -69.6427,
            -28.5429
          ],
          [
            -69.6375,
            -28.5439
          ],
          [
            -69.6305,
            -28.5406
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6458,
            -28.5412
          ],
          [
            -69.6414,
            -28.5421
          ],
          [
            -69.6345,
            -28.5395
          ],
          [
            -69.6305,
            -28.5406
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6677,
            -28.5556
          ],
          [
            -69.6635,
            -28.5615
          ],
          [
            -69.6525,
            -28.5673
          ],
          [
            -69.6462,
            -28.5689
          ],
          [
            -69.6437,
            -28.5743
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6462,
            -28.5591
          ],
          [
            -69.6465,
            -28.563
          ],
          [
            -69.6417,
            -28.5722
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5934,
            -28.5419
          ],
          [
            -69.5972,
            -28.5473
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5998,
            -28.5368
          ],
          [
            -69.5999,
            -28.5438
          ],
          [
            -69.5972,
            -28.5473
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5972,
            -28.5473
          ],
          [
            -69.6016,
            -28.5525
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "R\u00edo de los Mogotes",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.6016,
            -28.5525
          ],
          [
            -69.6001,
            -28.5593
          ],
          [
            -69.5975,
            -28.5627
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5895,
            -28.5537
          ],
          [
            -69.5896,
            -28.5563
          ],
          [
            -69.5975,
            -28.5627
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5959,
            -28.5346
          ],
          [
            -69.5958,
            -28.5385
          ],
          [
            -69.5934,
            -28.5419
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Quebrada s/n",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -69.5886,
            -28.5392
          ],
          [
            -69.5934,
            -28.5419
          ]
        ]
      }
    }
  ]
} as FeatureCollection<LineString, RiverProperties>

export const waterBodiesGeoJSON: FeatureCollection<Polygon, WaterBodyProperties> =
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "Laguna",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.4552,
              -28.4246
            ],
            [
              -69.4539,
              -28.4238
            ],
            [
              -69.4531,
              -28.4251
            ],
            [
              -69.4542,
              -28.4256
            ],
            [
              -69.4552,
              -28.4246
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Laguna",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.499,
              -28.3788
            ],
            [
              -69.4947,
              -28.3758
            ],
            [
              -69.4943,
              -28.3741
            ],
            [
              -69.4934,
              -28.3742
            ],
            [
              -69.4923,
              -28.3765
            ],
            [
              -69.4933,
              -28.3776
            ],
            [
              -69.493,
              -28.3795
            ],
            [
              -69.4981,
              -28.3813
            ],
            [
              -69.499,
              -28.3788
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Laguna",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.4783,
              -28.3364
            ],
            [
              -69.478,
              -28.337
            ],
            [
              -69.4791,
              -28.3374
            ],
            [
              -69.4791,
              -28.3363
            ],
            [
              -69.4783,
              -28.3364
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Laguna",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.4949,
              -28.3713
            ],
            [
              -69.494,
              -28.3712
            ],
            [
              -69.4941,
              -28.3723
            ],
            [
              -69.4949,
              -28.3713
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Laguna",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.4841,
              -28.3784
            ],
            [
              -69.482,
              -28.378
            ],
            [
              -69.4813,
              -28.3787
            ],
            [
              -69.4831,
              -28.3798
            ],
            [
              -69.4841,
              -28.3784
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Laguna",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.4913,
              -28.3645
            ],
            [
              -69.4921,
              -28.3646
            ],
            [
              -69.4917,
              -28.3635
            ],
            [
              -69.4888,
              -28.3639
            ],
            [
              -69.4913,
              -28.3645
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Laguna",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.4978,
              -28.3981
            ],
            [
              -69.4964,
              -28.3975
            ],
            [
              -69.497,
              -28.3989
            ],
            [
              -69.498,
              -28.3988
            ],
            [
              -69.4978,
              -28.3981
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Laguna",
        "kind": "perennial",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.4809,
              -28.4408
            ],
            [
              -69.4835,
              -28.441
            ],
            [
              -69.4828,
              -28.4394
            ],
            [
              -69.4806,
              -28.44
            ],
            [
              -69.4809,
              -28.4408
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Laguna intermitente",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.5353,
              -28.6228
            ],
            [
              -69.5356,
              -28.622
            ],
            [
              -69.5342,
              -28.6226
            ],
            [
              -69.5329,
              -28.6218
            ],
            [
              -69.5303,
              -28.622
            ],
            [
              -69.5296,
              -28.6242
            ],
            [
              -69.532,
              -28.6267
            ],
            [
              -69.5347,
              -28.6263
            ],
            [
              -69.5359,
              -28.6249
            ],
            [
              -69.5353,
              -28.6228
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Laguna intermitente",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.5377,
              -28.6304
            ],
            [
              -69.5368,
              -28.6307
            ],
            [
              -69.5377,
              -28.631
            ],
            [
              -69.5377,
              -28.6304
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Laguna intermitente",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.5475,
              -28.6426
            ],
            [
              -69.5464,
              -28.6422
            ],
            [
              -69.5459,
              -28.6429
            ],
            [
              -69.5471,
              -28.6436
            ],
            [
              -69.5475,
              -28.6426
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Laguna intermitente",
        "kind": "intermittent",
        "source": "IGN"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -69.5778,
              -28.3915
            ],
            [
              -69.5772,
              -28.3911
            ],
            [
              -69.5767,
              -28.3916
            ],
            [
              -69.5778,
              -28.3915
            ]
          ]
        ]
      }
    }
  ]
} as FeatureCollection<Polygon, WaterBodyProperties>

export const glaciersGeoJSON: FeatureCollection<Point, GlacierProperties> =
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "Glaciar de los Tambillos",
        "source": "IGN"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -69.752,
          -28.9656
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Glaciar El Potro",
        "source": "IGN"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -69.6032,
          -28.3955
        ]
      }
    }
  ]
} as FeatureCollection<Point, GlacierProperties>

export const boundaryGeoJSON: FeatureCollection<LineString, BoundaryProperties> =
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "Argentina - Chile Tramo 14",
        "source": "IGN"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -71.824,
            -40.578
          ],
          [
            -71.857,
            -40.592
          ],
          [
            -71.891,
            -40.556
          ],
          [
            -71.843,
            -40.525
          ],
          [
            -71.825,
            -40.421
          ],
          [
            -71.71,
            -40.425
          ],
          [
            -71.655,
            -40.355
          ],
          [
            -71.686,
            -40.293
          ],
          [
            -71.717,
            -40.279
          ],
          [
            -71.748,
            -40.307
          ],
          [
            -71.823,
            -40.233
          ],
          [
            -71.799,
            -40.137
          ],
          [
            -71.828,
            -40.091
          ],
          [
            -71.674,
            -40.104
          ],
          [
            -71.689,
            -40.033
          ],
          [
            -71.593,
            -39.912
          ],
          [
            -71.643,
            -39.854
          ],
          [
            -71.686,
            -39.855
          ],
          [
            -71.667,
            -39.808
          ],
          [
            -71.713,
            -39.724
          ],
          [
            -71.67,
            -39.682
          ],
          [
            -71.718,
            -39.637
          ],
          [
            -71.675,
            -39.564
          ],
          [
            -71.61,
            -39.628
          ],
          [
            -71.501,
            -39.637
          ],
          [
            -71.467,
            -39.557
          ],
          [
            -71.534,
            -39.528
          ],
          [
            -71.473,
            -39.494
          ],
          [
            -71.447,
            -39.451
          ],
          [
            -71.457,
            -39.37
          ],
          [
            -71.4,
            -39.35
          ],
          [
            -71.374,
            -39.283
          ],
          [
            -71.421,
            -39.151
          ],
          [
            -71.396,
            -39.046
          ],
          [
            -71.442,
            -38.981
          ],
          [
            -71.434,
            -38.929
          ],
          [
            -71.296,
            -38.873
          ],
          [
            -71.238,
            -38.802
          ],
          [
            -71.185,
            -38.815
          ],
          [
            -71.095,
            -38.755
          ],
          [
            -70.926,
            -38.763
          ],
          [
            -70.884,
            -38.702
          ],
          [
            -70.905,
            -38.667
          ],
          [
            -70.827,
            -38.596
          ],
          [
            -70.842,
            -38.538
          ],
          [
            -70.984,
            -38.43
          ],
          [
            -70.998,
            -38.291
          ],
          [
            -71.032,
            -38.25
          ],
          [
            -70.996,
            -38.171
          ],
          [
            -71.043,
            -38.123
          ],
          [
            -70.989,
            -38.087
          ],
          [
            -71.055,
            -38.044
          ],
          [
            -71.063,
            -37.97
          ],
          [
            -71.114,
            -37.952
          ],
          [
            -71.099,
            -37.902
          ],
          [
            -71.183,
            -37.858
          ],
          [
            -71.126,
            -37.821
          ],
          [
            -71.211,
            -37.697
          ],
          [
            -71.206,
            -37.648
          ],
          [
            -71.128,
            -37.588
          ],
          [
            -71.152,
            -37.539
          ],
          [
            -71.118,
            -37.469
          ],
          [
            -71.154,
            -37.401
          ],
          [
            -71.197,
            -37.384
          ],
          [
            -71.221,
            -37.275
          ],
          [
            -71.115,
            -37.208
          ],
          [
            -71.135,
            -37.148
          ],
          [
            -71.092,
            -37.115
          ],
          [
            -71.167,
            -36.997
          ],
          [
            -71.222,
            -36.978
          ],
          [
            -71.106,
            -36.971
          ],
          [
            -71.087,
            -36.933
          ],
          [
            -71.144,
            -36.929
          ],
          [
            -71.119,
            -36.869
          ],
          [
            -71.18,
            -36.841
          ],
          [
            -71.132,
            -36.815
          ],
          [
            -71.113,
            -36.679
          ],
          [
            -71.065,
            -36.715
          ],
          [
            -71.009,
            -36.691
          ],
          [
            -71.057,
            -36.619
          ],
          [
            -71.034,
            -36.473
          ],
          [
            -70.956,
            -36.504
          ],
          [
            -70.889,
            -36.466
          ],
          [
            -70.884,
            -36.396
          ],
          [
            -70.713,
            -36.428
          ],
          [
            -70.679,
            -36.39
          ],
          [
            -70.712,
            -36.345
          ],
          [
            -70.685,
            -36.305
          ],
          [
            -70.706,
            -36.273
          ],
          [
            -70.571,
            -36.176
          ],
          [
            -70.579,
            -36.14
          ],
          [
            -70.491,
            -36.179
          ],
          [
            -70.421,
            -36.156
          ],
          [
            -70.412,
            -36.058
          ],
          [
            -70.37,
            -36.039
          ],
          [
            -70.378,
            -35.99
          ],
          [
            -70.423,
            -35.972
          ],
          [
            -70.365,
            -35.924
          ],
          [
            -70.424,
            -35.915
          ],
          [
            -70.422,
            -35.877
          ],
          [
            -70.312,
            -35.813
          ],
          [
            -70.379,
            -35.788
          ],
          [
            -70.358,
            -35.75
          ],
          [
            -70.424,
            -35.641
          ],
          [
            -70.385,
            -35.605
          ],
          [
            -70.414,
            -35.528
          ],
          [
            -70.368,
            -35.521
          ],
          [
            -70.447,
            -35.463
          ],
          [
            -70.432,
            -35.318
          ],
          [
            -70.566,
            -35.299
          ],
          [
            -70.584,
            -35.267
          ],
          [
            -70.536,
            -35.199
          ],
          [
            -70.375,
            -35.17
          ],
          [
            -70.364,
            -35.006
          ],
          [
            -70.248,
            -34.799
          ],
          [
            -70.306,
            -34.747
          ],
          [
            -70.216,
            -34.683
          ],
          [
            -70.217,
            -34.611
          ],
          [
            -70.129,
            -34.486
          ],
          [
            -70.012,
            -34.412
          ],
          [
            -70.031,
            -34.288
          ],
          [
            -69.972,
            -34.25
          ],
          [
            -69.91,
            -34.292
          ],
          [
            -69.807,
            -34.248
          ],
          [
            -69.797,
            -34.21
          ],
          [
            -69.873,
            -34.131
          ],
          [
            -69.821,
            -34.015
          ],
          [
            -69.854,
            -33.964
          ],
          [
            -69.906,
            -33.963
          ],
          [
            -69.856,
            -33.892
          ],
          [
            -69.899,
            -33.847
          ],
          [
            -69.905,
            -33.771
          ],
          [
            -69.865,
            -33.717
          ],
          [
            -69.872,
            -33.539
          ],
          [
            -69.835,
            -33.516
          ],
          [
            -69.796,
            -33.421
          ],
          [
            -69.816,
            -33.39
          ],
          [
            -69.78,
            -33.385
          ],
          [
            -69.769,
            -33.343
          ],
          [
            -69.8,
            -33.288
          ],
          [
            -69.904,
            -33.273
          ],
          [
            -69.917,
            -33.244
          ],
          [
            -70.003,
            -33.323
          ],
          [
            -70.038,
            -33.27
          ],
          [
            -70.027,
            -33.232
          ],
          [
            -70.064,
            -33.205
          ],
          [
            -70.052,
            -33.135
          ],
          [
            -70.094,
            -33.051
          ],
          [
            -70.021,
            -33.009
          ],
          [
            -69.989,
            -32.899
          ],
          [
            -70.045,
            -32.87
          ],
          [
            -70.148,
            -32.728
          ],
          [
            -70.172,
            -32.622
          ],
          [
            -70.126,
            -32.577
          ],
          [
            -70.136,
            -32.487
          ],
          [
            -70.237,
            -32.429
          ],
          [
            -70.218,
            -32.333
          ],
          [
            -70.323,
            -32.267
          ],
          [
            -70.304,
            -32.136
          ],
          [
            -70.342,
            -32.109
          ],
          [
            -70.335,
            -32.07
          ],
          [
            -70.388,
            -32.045
          ],
          [
            -70.364,
            -32.025
          ],
          [
            -70.289,
            -32.052
          ],
          [
            -70.211,
            -31.957
          ],
          [
            -70.28,
            -31.884
          ],
          [
            -70.377,
            -31.885
          ],
          [
            -70.46,
            -31.844
          ],
          [
            -70.468,
            -31.698
          ],
          [
            -70.513,
            -31.69
          ],
          [
            -70.507,
            -31.652
          ],
          [
            -70.567,
            -31.6
          ],
          [
            -70.524,
            -31.19
          ],
          [
            -70.456,
            -31.084
          ],
          [
            -70.401,
            -31.167
          ],
          [
            -70.322,
            -31.043
          ],
          [
            -70.269,
            -31.043
          ],
          [
            -70.323,
            -30.928
          ],
          [
            -70.246,
            -30.729
          ],
          [
            -70.247,
            -30.634
          ],
          [
            -70.179,
            -30.512
          ],
          [
            -70.195,
            -30.492
          ],
          [
            -70.118,
            -30.432
          ],
          [
            -70.155,
            -30.347
          ],
          [
            -70.063,
            -30.394
          ],
          [
            -69.955,
            -30.386
          ],
          [
            -69.892,
            -30.351
          ],
          [
            -69.885,
            -30.219
          ],
          [
            -69.835,
            -30.22
          ],
          [
            -69.819,
            -30.189
          ],
          [
            -69.817,
            -30.128
          ],
          [
            -69.936,
            -30.12
          ],
          [
            -69.965,
            -30.085
          ],
          [
            -69.898,
            -29.958
          ],
          [
            -69.877,
            -29.862
          ],
          [
            -69.915,
            -29.793
          ],
          [
            -69.879,
            -29.726
          ],
          [
            -69.94,
            -29.654
          ],
          [
            -69.966,
            -29.414
          ],
          [
            -70.021,
            -29.384
          ],
          [
            -70.021,
            -29.33
          ],
          [
            -69.938,
            -29.25
          ],
          [
            -69.953,
            -29.189
          ],
          [
            -69.876,
            -29.139
          ],
          [
            -69.788,
            -29.133
          ],
          [
            -69.766,
            -28.899
          ],
          [
            -69.693,
            -28.771
          ],
          [
            -69.731,
            -28.684
          ],
          [
            -69.662,
            -28.583
          ],
          [
            -69.681,
            -28.471
          ],
          [
            -69.633,
            -28.43
          ],
          [
            -69.649,
            -28.396
          ],
          [
            -69.597,
            -28.392
          ],
          [
            -69.583,
            -28.352
          ],
          [
            -69.524,
            -28.33
          ],
          [
            -69.456,
            -28.184
          ],
          [
            -69.391,
            -28.226
          ],
          [
            -69.382,
            -28.182
          ],
          [
            -69.307,
            -28.129
          ],
          [
            -69.237,
            -27.967
          ],
          [
            -69.173,
            -27.971
          ],
          [
            -69.123,
            -27.901
          ],
          [
            -69.09,
            -27.722
          ],
          [
            -69.044,
            -27.697
          ],
          [
            -69.054,
            -27.619
          ],
          [
            -68.975,
            -27.56
          ],
          [
            -68.988,
            -27.524
          ],
          [
            -68.942,
            -27.519
          ],
          [
            -68.988,
            -27.447
          ],
          [
            -68.934,
            -27.444
          ],
          [
            -68.93,
            -27.409
          ],
          [
            -68.888,
            -27.398
          ],
          [
            -68.87,
            -27.318
          ],
          [
            -68.809,
            -27.301
          ],
          [
            -68.871,
            -27.246
          ],
          [
            -68.844,
            -27.161
          ],
          [
            -68.775,
            -27.1
          ]
        ]
      }
    }
  ]
} as FeatureCollection<LineString, BoundaryProperties>

export const minesGeoJSON: FeatureCollection<Point, MineProperties> =
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "Mina El Potro (Cobre - Oro)",
        "source": "IGN/SEGEMAR"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -69.5921,
          -28.4267
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Mina Josemar\u00eda (Cobre - Oro)",
        "source": "IGN/SEGEMAR"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -69.544,
          -28.4383
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Mina Vicu\u00f1a (Cobre - Oro - Plata)",
        "source": "IGN/SEGEMAR"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -69.6569,
          -28.4998
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Mina Mogotes (Cobre - Oro)",
        "source": "IGN/SEGEMAR"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -69.6519,
          -28.5675
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Mina Filo del Sol (Cobre - Oro - Plata)",
        "source": "IGN/SEGEMAR"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -69.6588,
          -28.4913
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "name": "Mina R\u00edo Las Tamber\u00edas",
        "source": "IGN/SEGEMAR"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -69.4548,
          -28.3255
        ]
      }
    }
  ]
} as FeatureCollection<Point, MineProperties>

/** Layer metadata for UI controls */
export const GEOLOGY_LAYERS = {
  rivers: { label: 'Rivers', color: '#3b82f6' },
  waterBodies: { label: 'Lakes', color: '#06b6d4' },
  glaciers: { label: 'Glaciers', color: '#a5f3fc' },
  boundary: { label: 'AR-CL Border', color: '#dc2626' },
  mines: { label: 'Mines', color: '#f59e0b' },
} as const

export type GeologyLayerKey = keyof typeof GEOLOGY_LAYERS
